import sys, os

# Ensure we can import agents from project root
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

import streamlit as st
from agents.orchestrator import Orchestrator

# Set page config
st.set_page_config(page_title="ExploreSmart AI", layout="wide")

# Title + description
st.markdown(
    """
    <div style="text-align: center;">
        <h1>🌍 ExploreSmart AI</h1>
        <p style="font-size: 18px; color: #666;">
        Discover hidden gems in a city & get personalized travel itineraries based on your tastes!
        </p>
    </div>
    """, unsafe_allow_html=True
)

# Sidebar for input
st.sidebar.header("Tell me about your trip")
city = st.sidebar.text_input("City", "Hyderabad")
interests_input = st.sidebar.text_input(
    "Interests (comma-separated)", "art, cafes, photography"
)
user_id = st.sidebar.text_input("User ID (for personalization)", "demo_user")

if st.sidebar.button("Generate Itinerary"):
    # Preprocess interests into list
    interests = [i.strip() for i in interests_input.split(",") if i.strip()]

    with st.spinner("Generating your personalized itinerary…"):
        orchestrator = Orchestrator()
        payload = {
            "city": city,
            "interests": interests,
            "user_id": user_id
        }
        result = orchestrator.run(payload)

    # Show results
    st.success("Here’s your personalized travel plan!")

    # Preferences
    st.subheader("🧠 Your Preference Profile")
    st.json(result.get("preferences", {}))

    # Itinerary
    st.subheader("🗺️ Your Personalized Itinerary")
    cards = result.get("itinerary", [])
    for item in cards:
        st.markdown(
            f"""
            <div style="
                border: 1px solid #ddd; 
                border-radius: 8px; 
                padding: 16px; 
                margin-bottom: 12px; 
                background-color: #f9f9f9;
            ">
                <h3 style="margin-bottom: 4px;">{item['order']}. {item['name']}</h3>
                <p style="margin: 2px 0;"><b>When:</b> {item['time_block']}</p>
                <p style="margin: 2px 0;"><b>Visit duration:</b> ~{item['estimated_visit_mins']} mins</p>
                <p style="margin: 2px 0;"><b>Address:</b> {item['address']}</p>
                <p style="margin: 2px 0;"><b>Description:</b> {item['short_desc']}</p>
                <p style="margin: 2px 0;">
                    <a href="{item['maps_url']}" target="_blank">
                        <button style="
                            background-color: #4CAF50;
                            color: white;
                            padding: 8px 12px;
                            border: none;
                            border-radius: 4px;
                            cursor: pointer;
                        ">
                        Open in Google Maps
                        </button>
                    </a>
                </p>
            </div>
            """, unsafe_allow_html=True
        )

    st.markdown("---")
    st.caption("Itinerary generated by ExploreSmart AI")

else:
    st.info("Enter your city and interests on the sidebar, then click **Generate Itinerary**.")

